chore(docs): add documentation to GitHub Scraper defining PAT permissions
liatrio/liatrio-otel-collector pull request #468
Opened 2024-08-20 21:26 UTC by gnmeyer

2024-08-20 21:50 UTC, jburns24 commented on receiver/gitproviderreceiver/README.md
> +It is recommend to use the [GitHub App Authentication Extension](https://github.com/liatrio/liatrio-otel-collector/tree/main/extension/githubappauthextension) for authentication because GitHub Apps u
```suggestion
It is recommend to use the [GitHub App Authentication Extension](https://github.com/liatrio/liatrio-otel-collector/tree/main/extension/githubappauthextension) for authentication. GitHub Apps offer better security through OAUTH, provide more granular control over permissions, and increase rate limits.
```

2024-08-20 22:13 UTC, adrielp commented on receiver/gitproviderreceiver/README.md
> +* repo:All
Shouldn't it just be `repo:read` or `read:repo`? There's nothing in here that writes to GitHub as all calls are read only.

2024-08-20 22:17 UTC, adrielp requested changes
A couple changes from myself and @jburns24. Once those are made then it'll be good to go!

2024-08-22 12:02 UTC, adrielp commented on receiver/gitproviderreceiver/docs/repo-perms-3.png
Do we not also need secret scanning alerts? 

Was this copy-pasta from the GitHub App Auth extension? If so, App auth is not 1 -> 1 with Fine grained tokens IIRC.

2024-08-23 20:35 UTC, gnmeyer commented on receiver/gitproviderreceiver/docs/repo-perms-3.png
These are the differing permissions offered between App Auth and Fine Grained Tokens. Ive updated the screenshot to show the list of permissions from the Fine Grained Token page.

| App Auth   | Fine Grained |
| ---------- | ------------ |
| Checks     | NA           |
| NA         | Custom properties |
| Packages   | NA           |
| Project    | NA           |
| Single File| NA           | 

git.repository.cve.count
The number of Common Vulnerabilities and Exposures (CVEs) in the repository.

This metric is covered by the [Repository security advisories](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-repository-security-advisories) and [Dependabot Alerts](https://docs.github.com/en/rest/authentication/permissions-required-for-fine-grained-personal-access-tokens?apiVersion=2022-11-28#repository-permissions-for-dependabot-alerts)

2024-08-23 20:37 UTC, adrielp approved these changes

2024-08-23 20:43 UTC, merged